@securityApp_HostAddress = http://localhost:5090

GET {{securityApp_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{securityApp_HostAddress}}/Link/SendLink/
Accept: application/json

###
